$kind: http-request
url: "{{baseUrl}}/v1/application_fees/:id/refund"
method: POST
headers:
  Content-Type: application/x-www-form-urlencoded
pathVariables:
  - key: id
    value: <string>
    description: "(Required) "
body:
  type: urlencoded
  content:
    - key: amount
      value: <integer>
      disabled: true
    - key: directive
      value: <string>
      disabled: true
    - key: expand[0]
      value: <string>
      disabled: true
      description: Specifies which fields in the response should be expanded.
    - key: expand[1]
      value: <string>
      disabled: true
      description: Specifies which fields in the response should be expanded.
order: 1000
