$kind: http-request
description: <p>Creates a configuration that describes the functionality and
  behavior of a PortalSession</p>
url: "{{baseUrl}}/v1/billing_portal/configurations"
method: POST
headers:
  Content-Type: application/x-www-form-urlencoded
body:
  type: urlencoded
  content:
    - key: business_profile[headline]
      value: <string>
      description: (Required) The business information shown to customers in the portal.
    - key: business_profile[privacy_policy_url]
      value: <string>
      description: (Required) The business information shown to customers in the portal.
    - key: business_profile[terms_of_service_url]
      value: <string>
      description: (Required) The business information shown to customers in the portal.
    - key: features[customer_update][enabled]
      value: <boolean>
      description: (Required) Information about the features available in the portal.
    - key: features[customer_update][allowed_updates][0]
      value: <string>
      description: (Required) Information about the features available in the portal.
    - key: features[customer_update][allowed_updates][1]
      value: <string>
      description: (Required) Information about the features available in the portal.
    - key: features[invoice_history][enabled]
      value: <boolean>
      description: (Required) Information about the features available in the portal.
    - key: features[payment_method_update][enabled]
      value: <boolean>
      description: (Required) Information about the features available in the portal.
    - key: features[subscription_cancel][enabled]
      value: <boolean>
      description: (Required) Information about the features available in the portal.
    - key: features[subscription_cancel][cancellation_reason][enabled]
      value: <boolean>
      description: (Required) Information about the features available in the portal.
    - key: features[subscription_cancel][cancellation_reason][options][0]
      value: <string>
      description: (Required) Information about the features available in the portal.
    - key: features[subscription_cancel][cancellation_reason][options][1]
      value: <string>
      description: (Required) Information about the features available in the portal.
    - key: features[subscription_cancel][mode]
      value: <string>
      description: (Required) Information about the features available in the portal.
    - key: features[subscription_cancel][proration_behavior]
      value: <string>
      description: (Required) Information about the features available in the portal.
    - key: features[subscription_update][default_allowed_updates][0]
      value: <string>
      description: (Required) Information about the features available in the portal.
    - key: features[subscription_update][default_allowed_updates][1]
      value: <string>
      description: (Required) Information about the features available in the portal.
    - key: features[subscription_update][enabled]
      value: <boolean>
      description: (Required) Information about the features available in the portal.
    - key: features[subscription_update][products][0][prices][0]
      value: <string>
      description: (Required) Information about the features available in the portal.
    - key: features[subscription_update][products][0][prices][1]
      value: <string>
      description: (Required) Information about the features available in the portal.
    - key: features[subscription_update][products][0][product]
      value: <string>
      description: (Required) Information about the features available in the portal.
    - key: features[subscription_update][products][1][prices][0]
      value: <string>
      description: (Required) Information about the features available in the portal.
    - key: features[subscription_update][products][1][prices][1]
      value: <string>
      description: (Required) Information about the features available in the portal.
    - key: features[subscription_update][products][1][product]
      value: <string>
      description: (Required) Information about the features available in the portal.
    - key: features[subscription_update][proration_behavior]
      value: <string>
      description: (Required) Information about the features available in the portal.
    - key: expand[0]
      value: <string>
      disabled: true
      description: Specifies which fields in the response should be expanded.
    - key: expand[1]
      value: <string>
      disabled: true
      description: Specifies which fields in the response should be expanded.
    - key: login_page[enabled]
      value: <boolean>
      disabled: true
      description: The hosted login page for this configuration. Learn more about the
        portal login page in our [integration
        docs](https://stripe.com/docs/billing/subscriptions/integrating-customer-portal#share).
order: 2000
