$kind: http-request
description: >-
  <p>Updates the specified application fee refund by setting the values of the
  parameters passed. Any parameters not provided will be left unchanged.</p>


  <p>This request only accepts metadata as an argument.</p>
url: "{{baseUrl}}/v1/application_fees/:fee/refunds/:id"
method: POST
headers:
  Content-Type: application/x-www-form-urlencoded
pathVariables:
  - key: fee
    value: <string>
    description: "(Required) "
  - key: id
    value: <string>
    description: "(Required) "
body:
  type: urlencoded
  content:
    - key: expand[0]
      value: <string>
      disabled: true
      description: Specifies which fields in the response should be expanded.
    - key: expand[1]
      value: <string>
      disabled: true
      description: Specifies which fields in the response should be expanded.
order: 3000
